# Generated by Django 4.0 on 2022-01-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0002_controlmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processmachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('operation_no', models.IntegerField()),
                ('process_uploadfile', models.FileField(upload_to='documents/')),
            ],
            options={
                'db_table': 'processmachine',
            },
        ),
    ]
