# Generated by Django 4.0 on 2022-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0003_processmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmachine',
            name='process_uploadfile',
            field=models.FileField(upload_to='documents2/'),
        ),
    ]
