# Generated by Django 4.0 on 2022-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0004_alter_processmachine_process_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmachine',
            name='control_uploadfile',
            field=models.FileField(upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='processmachine',
            name='process_uploadfile',
            field=models.FileField(upload_to='media2/documents2/'),
        ),
    ]
