# Generated by Django 4.0 on 2022-01-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0005_alter_controlmachine_control_uploadfile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Processmachine',
        ),
        migrations.AlterField(
            model_name='controlmachine',
            name='control_uploadfile',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
