# Generated by Django 4.0 on 2022-01-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0006_delete_processmachine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processmachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('operation_no', models.IntegerField()),
                ('process_uploadfile', models.FileField(upload_to='process_files/')),
            ],
            options={
                'db_table': 'processmachine',
            },
        ),
        migrations.AlterField(
            model_name='controlmachine',
            name='control_uploadfile',
            field=models.FileField(upload_to='control_files/'),
        ),
    ]
