# Generated by Django 4.0 on 2022-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0007_processmachine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillmachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('operation_no', models.IntegerField()),
                ('skill_uploadfile', models.FileField(upload_to='skill_files/')),
            ],
            options={
                'db_table': 'skillmachine',
            },
        ),
    ]
