# Generated by Django 4.0 on 2022-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0008_skillmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainmachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('operation_no', models.IntegerField()),
                ('maintain_uploadfile', models.FileField(upload_to='maintain_files/')),
            ],
            options={
                'db_table': 'maintainmachine',
            },
        ),
    ]
