# Generated by Django 4.0 on 2022-01-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0009_maintainmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swsmachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('operation_no', models.IntegerField()),
                ('sws_uploadfile', models.FileField(upload_to='sws_files/')),
            ],
            options={
                'db_table': 'swsmachine',
            },
        ),
    ]
