# Generated by Django 4.0 on 2022-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0010_swsmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safetymachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('operation_no', models.IntegerField()),
                ('safety_uploadfile', models.FileField(upload_to='safety_files/')),
            ],
            options={
                'db_table': 'safetymachine',
            },
        ),
    ]
