# Generated by Django 4.0 on 2022-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0011_safetymachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfdmachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('operation_no', models.IntegerField()),
                ('pfd_uploadfile', models.FileField(upload_to='pfd_files/')),
            ],
            options={
                'db_table': 'pfdmachine',
            },
        ),
    ]
