# Generated by Django 4.0 on 2022-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0012_pfdmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaugesmachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('operation_no', models.IntegerField()),
                ('gauges_uploadfile', models.FileField(upload_to='gauges_files/')),
            ],
            options={
                'db_table': 'gaugesmachine',
            },
        ),
    ]
